default_values = {
    'pyml':
    {
        'bg':None,
        'bo-s':None,
        'bo-fg':None,
        'bo-bg':None,
        'm-t':0,
        'm-b':0,
        'm-l':0,
        'm-r':0,
        'p-t':0,
        'p-b':0,
        'p-l':0,
        'p-r':0,
        'w':0, 'h':0,
        'x':0, 'y':0,
        't-a-h':"left",
        't-a-v':"top",
        't-fg':None,
        't-bg':None
    },
    'row':{
        'bg':None,
        'bo-s':None,
        'bo-fg':None,
        'bo-bg':None,
        'm-t':0,
        'm-b':0,
        'm-l':0,
        'm-r':0,
        'p-t':0,
        'p-b':0,
        'p-l':0,
        'p-r':0,
        'w':'100%', 'h':0,
        'x':0, 'y':0,
        't-a-h':"left",
        't-a-v':"top",
        't-fg':"inherit",
        't-bg':None
    },
    'rect':{
        'bg':None,
        'bo-s':"classic",
        'bo-fg':None,
        'bo-bg':None,
        'm-t':0,
        'm-b':0,
        'm-l':0,
        'm-r':0,
        'p-t':1,
        'p-b':1,
        'p-l':1,
        'p-r':1,
        'w':0, 'h':0,
        'x':"inherit", 'y':"inherit",
        't-a-h':"left",
        't-a-v':"top",
        't-fg':"inherit",
        't-bg':None
    },
    'txt':{
        'bg':None,
        'bo-s':None,
        'bo-fg':None,
        'bo-bg':None,
        'm-t':1,
        'm-b':1,
        'm-l':1,
        'm-r':1,
        'p-t':0,
        'p-b':0,
        'p-l':0,
        'p-r':0,
        'w':-1, 'h':-1,
        'x':"inherit", 'y':"inherit",
        't-a-h':"left",
        't-a-v':"top",
        't-fg':"inherit",
        't-bg':None
    },
    'unrecognized':{
        'bg':None,
        'bo-s':None,
        'bo-fg':None,
        'bo-bg':None,
        'm-t':0,
        'm-b':0,
        'm-l':0,
        'm-r':0,
        'p-t':0,
        'p-b':0,
        'p-l':0,
        'p-r':0,
        'w':0, 'h':0,
        'x':0, 'y':0,
        't-a-h':"left",
        't-a-v':"top",
        't-fg':None,
        't-bg':None
    }
}